"""RAM配置の正典。段D/Eの動的配置後。ROM窓の呼び先は対象外。

REGIONSのbase/sizeからFIELDSの番地とアセンブル用EQUを生成する。
別名は同じMM_名を参照し、移設時は対象構造のbaseだけを変更する。
profileが*-test/measureの範囲は通常ビルドでは使わない。
自己検査・測定域も専用に確保し、通常状態とは重ねない。

REGIONSは固定域とCPUスタック・VRAMだけを記述する。
利用者領域の可変構造はDYNAMIC_STRUCTURES、初期値はCONSTANTS、
実行時の位置はMEMDYNのポインタで表す。MM_SYNTH_DATAは合成ROM専用の
結果置場の起点であり、通常ROMの固定割当てではない。
"""
from dataclasses import dataclass


@dataclass(frozen=True)
class Region:
    name: str
    base: int
    size: int
    retention: str
    use: str
    profile: str = "normal"


REGIONS = (
    Region('SINGLE', 0xE600, 98, '一時', '単精度演算・PEEK/POKE値受渡し', 'normal'),
    Region('FIN', 0xE662, 46, '一時', '単精度文字列入力', 'normal'),
    Region('FOUT', 0xE690, 44, '一時', '単精度文字列出力', 'normal'),
    Region('TRUNC', 0xE6BC, 3, '一時', '単精度整数化', 'normal'),
    Region('DOUBLE_WORK', 0xE6BF, 106, '一時', '展開倍精度・演算', 'normal'),
    Region('DOUBLE', 0xE729, 162, '一時', '倍精度演算・文字列入出力', 'normal'),
    Region('VALUE_STACK', 0xE7CB, 288, '一時', '式評価32スロット×9B', 'normal'),
    Region('LITERAL', 0xE8EB, 35, '一時', '式スタック位置・字句・整数乗算', 'normal'),
    Region('SQR', 0xE90E, 17, '一時', '平方根', 'normal'),
    Region('SINCOS', 0xE91F, 62, '一時', 'SIN/COS/TAN', 'normal'),
    Region('ATN', 0xE95D, 19, '一時', 'ATN', 'normal'),
    Region('EXP', 0xE970, 20, '一時', 'EXP', 'normal'),
    Region('LOG', 0xE984, 24, '一時', 'LOG', 'normal'),
    Region('POLY', 0xE99C, 9, '一時', '超越関数多項式', 'normal'),
    Region('RND', 0xEFB2, 8, '保持', '乱数状態（CLEARでは保持）', 'normal'),
    Region('LIST', 0xECB2, 208, '一時', 'LIST・行変換', 'normal'),
    Region('STRING_USED', 0xF220, 12, '保持', '長文字列最大96ページの使用ビット', 'normal'),
    Region('STRING_TMP', 0xE9A5, 255, '一時', '文字列結果', 'normal'),
    Region('STRING_ARG', 0xEAA4, 255, '一時', '文字列第1引数退避', 'normal'),
    Region('STRING_ACC', 0xEBA3, 255, '一時', '文字列連結蓄積', 'normal'),
    Region('STRING_WORK', 0xECA2, 16, '一時', '文字列操作・RESUME一時カウンタ', 'normal'),
    Region('STMT_START', 0xFFEB, 2, '保持（毎文更新）', 'RESUME NEXT文頭', 'normal'),
    Region('STRCMP', 0xECB2, 256, '一時', '文字列比較左辺退避（棚卸し追補）', 'normal'),
    Region('RUN', 0xEFBC, 90, '保持/一時', '実行状態（offset 1–5・82–83は保持、他一時）', 'normal'),
    Region('VAR_FREE', 0xF016, 2, '一時', '空き変数レコードポインタ', 'normal'),
    Region('RUN_EXTRA_HEAD', 0xF018, 8, '一時', 'キーワード・比較・DATA希望型', 'normal'),
    Region('DATA_POSITION', 0xFFED, 7, '保持', 'DATA保存位置（編集/CLEAR/NEW/LOAD/RUNで無効化）', 'normal'),
    Region('DATA_WORK', 0xF020, 5, '一時', 'DATA走査の本線退避・符号', 'normal'),
    Region('CONT_POSITION', 0xFFF4, 6, '保持', 'CONT保存位置（編集/CLEAR/NEW/LOAD/RUNで無効化）', 'normal'),
    Region('RUN_EXTRA_TAIL', 0xF025, 43, '保持/一時', '整数演算・配列・IF作業', 'normal'),
    Region('ON_ERROR', 0xFFFA, 4, '保持', 'ON ERROR行番号・ACTIVE・ERR', 'normal'),
    Region('RESUME', 0xF21A, 6, '保持', 'RESUME保存位置3ポインタ', 'normal'),
    Region('STR_ARG_LEN', 0xF050, 1, '一時', '文字列第1引数長', 'normal'),
    Region('STR_ACC_LEN', 0xF051, 1, '一時', '文字列連結長', 'normal'),
    Region('RUN_INPUT', 0xF052, 88, '一時', 'INPUT・配列代入・数値字句', 'normal'),
    Region('SECTOR', 0xEDB2, 256, '一時', 'FILES/LOAD/SAVE共用セクタバッファ', 'normal'),
    Region('DISK_STATE', 0xF0AA, 9, '一時', 'main/sub READ状態', 'normal'),
    Region('DISK_CHR', 0xF0B3, 3, '一時', '任意座標READ・論理送信済', 'normal'),
    Region('FILES_FAT', 0xEEB2, 256, '一時', 'FILES FAT', 'normal'),
    Region('FILES', 0xF0B6, 27, '一時', 'FILES表示・走査', 'normal'),
    Region('LOAD', 0xF0D1, 23, '一時', 'LOAD走査・名前', 'normal'),
    Region('SAVE', 0xF0E8, 56, '一時', 'SAVE捕捉・書込・KILL/NAME状態', 'normal'),
    Region('SAVE_FAT', 0xEEB2, 256, '一時', 'SAVE/KILL FAT', 'normal'),
    Region('SAVE_ALLOC', 0xF22C, 12, '一時', 'SAVE割当（最大12個の2KB単位）', 'normal'),
    Region('SCREEN', 0xF126, 4, '保持', '画面行・桁・行頭', 'normal'),
    Region('KEY_OLD', 0xF12A, 12, '保持', '前回キー行列', 'normal'),
    Region('KEY_NEW', 0xF136, 12, '一時', '今回キー行列', 'normal'),
    Region('LINE', 0xF142, 82, '保持', '入力長・入力行80B・挿入モード（LOADと共用）', 'normal'),
    Region('LEXER', 0xF194, 34, '一時', '字句解析・誤り', 'normal'),
    Region('VALUES', 0xF1B6, 18, '一時', 'CUR/RHS 型・値', 'normal'),
    Region('REPEAT', 0xF1C8, 6, '保持', 'キーリピート', 'normal'),
    Region('RELAY', 0xF1CE, 4, '保持/一時', '拡張バンク再入フラグ・ポート退避', 'normal'),
    Region('INKEY', 0xF1D2, 24, '保持', 'INKEY状態', 'normal'),
    Region('INKEY_QUEUE', 0xF1EA, 32, '保持', 'INKEYキュー', 'normal'),
    Region('PROGRAM_WORK', 0xFF80, 29, '一時', '本文編集・LISTポインタ', 'normal'),
    Region('MEMDYN', 0xF20A, 16, '保持/一時', 'LIMIT・ヒープ開始/末尾・空き上端・FOR/GOSUB位置・捕捉上端・検索種別', 'normal'),
    Region('CPU_STACK', 0xF238, 400, '一時', 'CPUスタック（下限未検査、上端から下へ）', 'normal'),
    Region('TEXT', 0xF3C8, 3000, '保持', 'テキストVRAM（25行×120B、作業域として使用禁止）', 'normal'),
    Region('EXT_TEST_LOW', 0xFF9D, 8, '一時', 'EXT_BANK_ST_*・排他的なSAVE合成試験（通常ビルドでは使わない）', 'ext-test'),
    Region('EXT_TEST_HIGH', 0xFFA5, 5, '一時', 'EXT_BANK_ST_*（通常ビルドでは使わない）', 'ext-test'),
    Region('VSYNC_TEST', 0xFFAA, 13, '一時', 'vsync_regcheck（通常ビルドでは使わない）', 'vsync-test'),
    Region('MEASURE_LOW', 0xFFB7, 5, '一時', 'M6IB/M6IH測定（通常ビルドでは使わない）', 'measure'),
    Region('MEASURE_REGS', 0xFFBC, 38, '一時', 'M6IAレジスタ・バンク写し（通常ビルドでは使わない）', 'measure'),
    Region('MEASURE_HIGH', 0xFFE2, 6, '一時', 'M6IA/M6II/M6IK測定（通常ビルドでは使わない）', 'measure'),
    Region('INKEY_TEST', 0xFFE8, 3, '一時', 'INKEY頑健性ドライバ専用（通常ビルドでは使わない）', 'inkey-test'),
)

# 排他的なコマンド経路に限って共用する。割込みは画面・キー・INKEYのみ。
OVERLAPS = {
    frozenset(("FILES_FAT", "SAVE_FAT")): "FILES/LOADはbank1の独立した文入口、SAVE/KILLはbank2の文入口。互いを呼ばず、SAVEの入れ子はLIST捕捉(bank3)のみ。各入口でFATを読み直し、文の終了後に保持しない。256BのLDIR全体を共用。",
    frozenset(("LIST", "STRCMP")): "LISTNUM_STARTは行の登録・LIST_RENDER_TEXT（SAVE捕捉も同経路）からのみ呼び、数値書式化はMBFだけを使用。S9E_CMPは文字列式評価だけから呼び、LIST/行登録を呼ばない。LIST文の引数は空白・行末のみで式を評価しない。",
}

# 名前 -> (構造, 構造内のオフセット)。同一番地のバンク別名は同じ名前を使う。
FIELDS = {
    'MM_USER_LIMIT': ('MEMDYN', 0),
    'MM_HEAP_START': ('MEMDYN', 2),
    'MM_HEAP_END': ('MEMDYN', 4),
    'MM_FREE_TOP': ('MEMDYN', 6),
    'MM_RUN_FOR_STACK': ('MEMDYN', 8),
    'MM_RUN_GOSUB_STACK': ('MEMDYN', 10),
    'MM_CAPTURE_END': ('MEMDYN', 12),
    'MM_HEAP_KIND': ('MEMDYN', 14),
    'MM_S2_CAPTURE_BASE': ('MEMDYN', 4),

    "MM_IK_TEST_SEEN": ("INKEY_TEST", 0),
    "MM_IK_TEST_CHAR": ("INKEY_TEST", 1),
    "MM_IK_TEST_POLL": ("INKEY_TEST", 2),
    "MM_VAL_SP": ('LITERAL', 0),
    "MM_LIT_BUF": ('LITERAL', 1),
    "MM_LIT_LEN": ('LITERAL', 25),
    "MM_LIT_HASDOT": ('LITERAL', 26),
    "MM_LIT_HASEXP": ('LITERAL', 27),
    "MM_LIT_HASSUFFIX": ('LITERAL', 28),
    "MM_MULI_SIGN": ('LITERAL', 29),
    "MM_MULI_A": ('LITERAL', 30),
    "MM_MULI_B": ('LITERAL', 32),
    "MM_MULI_COUNT": ('LITERAL', 34),
    "MM_M6IA_REG_PRE": ('MEASURE_REGS', 0),
    "MM_M6IA_REG_POST": ('MEASURE_REGS', 12),
    "MM_M6IA_PORT71_PRE": ('MEASURE_REGS', 24),
    "MM_M6IA_PORT32_PRE": ('MEASURE_REGS', 25),
    "MM_M6IA_PORT71_POST": ('MEASURE_REGS', 26),
    "MM_M6IA_PORT32_POST": ('MEASURE_REGS', 27),
    "MM_M6IA_BANK_PRE": ('MEASURE_REGS', 28),
    "MM_M6IA_BANK_POST": ('MEASURE_REGS', 32),
    "MM_M6IA_ITERATION_DONE": ('MEASURE_REGS', 36),
    "MM_M6IA_REPEAT_DONE": ('MEASURE_REGS', 37),
    "MM_M6IA_REPEAT_LEFT": ('MEASURE_HIGH', 0),
    "MM_M6IB_BRANCH_TAG": ('MEASURE_LOW', 4),
    'MM_MBF_OPA': ('SINGLE', 0),
    'MM_MBF_OPB': ('SINGLE', 4),
    'MM_MBF_RES': ('SINGLE', 8),
    'MM_MBF_STATUS': ('SINGLE', 12),
    'MM_MBF_IN_INT': ('SINGLE', 13),
    'MM_MBF_OUT_CMP': ('SINGLE', 15),
    'MM_UA_SIGN': ('SINGLE', 16),
    'MM_UA_EXP': ('SINGLE', 17),
    'MM_UA_M2': ('SINGLE', 18),
    'MM_UA_M1': ('SINGLE', 19),
    'MM_UA_M0': ('SINGLE', 20),
    'MM_UB_SIGN': ('SINGLE', 22),
    'MM_UB_EXP': ('SINGLE', 23),
    'MM_UB_M2': ('SINGLE', 24),
    'MM_UB_M1': ('SINGLE', 25),
    'MM_UB_M0': ('SINGLE', 26),
    'MM_BIG_SIGN': ('SINGLE', 32),
    'MM_BIG_EXP': ('SINGLE', 33),
    'MM_BIG_M2': ('SINGLE', 34),
    'MM_BIG_M1': ('SINGLE', 35),
    'MM_BIG_M0': ('SINGLE', 36),
    'MM_BIG_MG': ('SINGLE', 37),
    'MM_SML_SIGN': ('SINGLE', 38),
    'MM_SML_EXP': ('SINGLE', 39),
    'MM_SML_M2': ('SINGLE', 40),
    'MM_SML_M1': ('SINGLE', 41),
    'MM_SML_M0': ('SINGLE', 42),
    'MM_SML_MG': ('SINGLE', 43),
    'MM_RES_SIGN': ('SINGLE', 44),
    'MM_RES_EXP': ('SINGLE', 45),
    'MM_TRUNC_HADFRAC': ('TRUNC', 0),
    'MM_TRUNC_SIGN': ('TRUNC', 1),
    'MM_TRUNC_FRACBITS': ('TRUNC', 2),
    'MM_WK_STICKY': ('SINGLE', 48),
    'MM_WK_BORROW': ('SINGLE', 52),
    'MM_WK_SHIFT': ('SINGLE', 49),
    'MM_WK_TMP': ('SINGLE', 50),
    'MM_MUL_R5': ('SINGLE', 64),
    'MM_MUL_R4': ('SINGLE', 65),
    'MM_MUL_R3': ('SINGLE', 66),
    'MM_MUL_R2': ('SINGLE', 67),
    'MM_MUL_R1': ('SINGLE', 68),
    'MM_MUL_R0': ('SINGLE', 69),
    'MM_MUL_C5': ('SINGLE', 70),
    'MM_MUL_C4': ('SINGLE', 71),
    'MM_MUL_C3': ('SINGLE', 72),
    'MM_MUL_C2': ('SINGLE', 73),
    'MM_MUL_C1': ('SINGLE', 74),
    'MM_MUL_C0': ('SINGLE', 75),
    'MM_WK_S': ('SINGLE', 76),
    'MM_WK_DROUND_MODE': ('SINGLE', 79),
    'MM_WK_MUL_ROUNDMODE': ('SINGLE', 78),
    'MM_DIV_Q3': ('SINGLE', 80),
    'MM_DIV_Q2': ('SINGLE', 81),
    'MM_DIV_Q1': ('SINGLE', 82),
    'MM_DIV_Q0': ('SINGLE', 83),
    'MM_DIV_R3': ('SINGLE', 84),
    'MM_DIV_R2': ('SINGLE', 85),
    'MM_DIV_R1': ('SINGLE', 86),
    'MM_DIV_R0': ('SINGLE', 87),
    'MM_DIV_T3': ('SINGLE', 88),
    'MM_DIV_T2': ('SINGLE', 89),
    'MM_DIV_T1': ('SINGLE', 90),
    'MM_DIV_T0': ('SINGLE', 91),
    'MM_DIV_B3': ('SINGLE', 92),
    'MM_DIV_B2': ('SINGLE', 93),
    'MM_DIV_B1': ('SINGLE', 94),
    'MM_DIV_B0': ('SINGLE', 95),
    'MM_WK_REMZERO': ('SINGLE', 96),
    'MM_WK_DIVINIT': ('SINGLE', 97),
    'MM_FIN_BUF': ('FIN', 0),
    'MM_FIN_LEN': ('FIN', 24),
    'MM_FIN_POS': ('FIN', 25),
    'MM_FIN_SIGN': ('FIN', 26),
    'MM_FIN_ACC3': ('FIN', 27),
    'MM_FIN_ACC2': ('FIN', 28),
    'MM_FIN_ACC1': ('FIN', 29),
    'MM_FIN_ACC0': ('FIN', 30),
    'MM_FIN_FRACDIG': ('FIN', 31),
    'MM_FIN_SEENDOT': ('FIN', 32),
    'MM_FIN_EXPSIGN': ('FIN', 33),
    'MM_FIN_EXPVAL': ('FIN', 34),
    'MM_FIN_HASHASH': ('FIN', 35),
    'MM_FIN_HASD': ('FIN', 36),
    'MM_FIN_ISDOUBLE': ('FIN', 37),
    'MM_FIN_SCALE': ('FIN', 38),
    'MM_WK_FINDIGIT': ('FIN', 39),
    'MM_FIN_HASBANG': ('FIN', 43),
    'MM_FIN_REP01_COUNT': ('FIN', 44),
    'MM_FIN_REP01_MODE': ('FIN', 45),
    'MM_FOUT_SIGN': ('FOUT', 0),
    'MM_FOUT_E': ('FOUT', 1),
    'MM_FOUT_SCALECNT': ('FOUT', 2),
    'MM_FOUT_INT3': ('FOUT', 3),
    'MM_FOUT_INT2': ('FOUT', 4),
    'MM_FOUT_INT1': ('FOUT', 5),
    'MM_FOUT_INT0': ('FOUT', 6),
    'MM_WK_REM10': ('FOUT', 7),
    'MM_FOUT_DIGITS': ('FOUT', 8),
    'MM_FOUT_NSIG': ('FOUT', 14),
    'MM_FOUT_ISFIXED': ('FOUT', 15),
    'MM_FOUT_BUF': ('FOUT', 16),
    'MM_FOUT_LEN': ('FOUT', 32),
    'MM_WK_FOUTLOOP': ('FOUT', 33),
    'MM_FOUT_DIGIDX': ('FOUT', 34),
    'MM_FOUT_R_START': ('FOUT', 35),
    'MM_FOUT_R_COUNT': ('FOUT', 36),
    'MM_FOUT_R_CHAR': ('FOUT', 37),
    'MM_FOUT_SHIFTCNT': ('FOUT', 38),
    'MM_FOUT_SHIFTORIG': ('FOUT', 39),
    'MM_FOUT_ORIGVAL': ('FOUT', 40),
    'MM_FOUT_DREMAIN': ('DOUBLE_WORK', 98),
    'MM_FOUT_DSCALE_NEG': ('DOUBLE_WORK', 99),
    'MM_WK_DFOUT_APPLY': ('DOUBLE_WORK', 100),
    'MM_FOUT_DSHIFTCNT': ('DOUBLE_WORK', 101),
    'MM_FOUT_DGUARD': ('DOUBLE_WORK', 102),
    'MM_WK_M10_T2': ('DOUBLE_WORK', 103),
    'MM_WK_M10_T1': ('DOUBLE_WORK', 104),
    'MM_WK_M10_T0': ('DOUBLE_WORK', 105),
    'MM_DA_SIGN': ('DOUBLE_WORK', 0),
    'MM_DA_EXP': ('DOUBLE_WORK', 1),
    'MM_DA_M6': ('DOUBLE_WORK', 2),
    'MM_DA_M5': ('DOUBLE_WORK', 3),
    'MM_DA_M4': ('DOUBLE_WORK', 4),
    'MM_DA_M3': ('DOUBLE_WORK', 5),
    'MM_DA_M2': ('DOUBLE_WORK', 6),
    'MM_DA_M1': ('DOUBLE_WORK', 7),
    'MM_DA_M0': ('DOUBLE_WORK', 8),
    'MM_DB_SIGN': ('DOUBLE_WORK', 9),
    'MM_DB_EXP': ('DOUBLE_WORK', 10),
    'MM_DB_M6': ('DOUBLE_WORK', 11),
    'MM_DB_M5': ('DOUBLE_WORK', 12),
    'MM_DB_M4': ('DOUBLE_WORK', 13),
    'MM_DB_M3': ('DOUBLE_WORK', 14),
    'MM_DB_M2': ('DOUBLE_WORK', 15),
    'MM_DB_M1': ('DOUBLE_WORK', 16),
    'MM_DB_M0': ('DOUBLE_WORK', 17),
    'MM_WK_DS': ('DOUBLE_WORK', 18),
    'MM_PR9': ('DOUBLE_WORK', 32),
    'MM_PR8': ('DOUBLE_WORK', 33),
    'MM_PR7': ('DOUBLE_WORK', 34),
    'MM_PR6': ('DOUBLE_WORK', 35),
    'MM_PR5': ('DOUBLE_WORK', 36),
    'MM_PR4': ('DOUBLE_WORK', 37),
    'MM_PR3': ('DOUBLE_WORK', 38),
    'MM_PR2': ('DOUBLE_WORK', 39),
    'MM_PR1': ('DOUBLE_WORK', 40),
    'MM_PR0': ('DOUBLE_WORK', 41),
    'MM_MC9': ('DOUBLE_WORK', 42),
    'MM_MC8': ('DOUBLE_WORK', 43),
    'MM_MC7': ('DOUBLE_WORK', 44),
    'MM_MC6': ('DOUBLE_WORK', 45),
    'MM_MC5': ('DOUBLE_WORK', 46),
    'MM_MC4': ('DOUBLE_WORK', 47),
    'MM_MC3': ('DOUBLE_WORK', 48),
    'MM_MC2': ('DOUBLE_WORK', 49),
    'MM_MC1': ('DOUBLE_WORK', 50),
    'MM_MC0': ('DOUBLE_WORK', 51),
    'MM_WK_DLOOP': ('DOUBLE_WORK', 52),
    'MM_PRA': ('DOUBLE_WORK', 53),
    'MM_MCA': ('DOUBLE_WORK', 54),
    'MM_DQ7': ('DOUBLE_WORK', 64),
    'MM_DQ6': ('DOUBLE_WORK', 65),
    'MM_DQ5': ('DOUBLE_WORK', 66),
    'MM_DQ4': ('DOUBLE_WORK', 67),
    'MM_DQ3': ('DOUBLE_WORK', 68),
    'MM_DQ2': ('DOUBLE_WORK', 69),
    'MM_DQ1': ('DOUBLE_WORK', 70),
    'MM_DQ0': ('DOUBLE_WORK', 71),
    'MM_DR7': ('DOUBLE_WORK', 72),
    'MM_DR6': ('DOUBLE_WORK', 73),
    'MM_DR5': ('DOUBLE_WORK', 74),
    'MM_DR4': ('DOUBLE_WORK', 75),
    'MM_DR3': ('DOUBLE_WORK', 76),
    'MM_DR2': ('DOUBLE_WORK', 77),
    'MM_DR1': ('DOUBLE_WORK', 78),
    'MM_DR0': ('DOUBLE_WORK', 79),
    'MM_DT7': ('DOUBLE_WORK', 80),
    'MM_DT6': ('DOUBLE_WORK', 81),
    'MM_DT5': ('DOUBLE_WORK', 82),
    'MM_DT4': ('DOUBLE_WORK', 83),
    'MM_DT3': ('DOUBLE_WORK', 84),
    'MM_DT2': ('DOUBLE_WORK', 85),
    'MM_DT1': ('DOUBLE_WORK', 86),
    'MM_DT0': ('DOUBLE_WORK', 87),
    'MM_DDV7': ('DOUBLE_WORK', 88),
    'MM_DDV6': ('DOUBLE_WORK', 89),
    'MM_DDV5': ('DOUBLE_WORK', 90),
    'MM_DDV4': ('DOUBLE_WORK', 91),
    'MM_DDV3': ('DOUBLE_WORK', 92),
    'MM_DDV2': ('DOUBLE_WORK', 93),
    'MM_DDV1': ('DOUBLE_WORK', 94),
    'MM_DDV0': ('DOUBLE_WORK', 95),
    'MM_WK_DREMZERO': ('DOUBLE_WORK', 96),
    'MM_WK_DINIT': ('DOUBLE_WORK', 97),
    'MM_MBF_DOUBLE_RAM_BASE': ('DOUBLE', 0),
    'MM_PUD_VALUE': ('LEXER', 26),
    'MM_PUD_PLACE': ('LEXER', 28),
    'MM_PUD_DIGIT': ('LEXER', 30),
    'MM_PUD_STARTED': ('LEXER', 31),
    'MM_ERROR_KIND': ('LEXER', 32),
    'MM_ERROR_IS_RUNTIME': ('LEXER', 33),
    'MM_CUR_TYPE': ('VALUES', 0),
    'MM_CUR_DATA': ('VALUES', 1),
    'MM_RHS_TYPE': ('VALUES', 9),
    'MM_RHS_DATA': ('VALUES', 10),
    'MM_INTERP_EXT_RAM_BASE': ('VALUE_STACK', 0),
    'MM_RUN_STMT_KIND': ('RUN', 0),
    'MM_RUN_CUR_RECORD': ('RUN', 1),
    'MM_RUN_CUR_LINENO': ('RUN', 3),
    'MM_RUN_CTRL': ('RUN', 5),
    'MM_IDENT_BUF': ('RUN', 6),
    'MM_IDENT_LEN': ('RUN', 14),
    'MM_IDENT_KIND': ('RUN', 15),
    'MM_RUN_ASSIGN_KIND': ('RUN', 16),
    'MM_RUN_ASSIGN_NAME': ('RUN', 17),
    'MM_RUN_FOR_VARNAME': ('RUN', 25),
    'MM_RUN_FOR_LIMIT_TYPE': ('RUN', 33),
    'MM_RUN_FOR_LIMIT_DATA': ('RUN', 34),
    'MM_RUN_FOR_STEP_TYPE': ('RUN', 38),
    'MM_RUN_FOR_STEP_DATA': ('RUN', 39),
    'MM_RUN_FOR_FRAME_PTR': ('RUN', 43),
    'MM_RUN_FOR_CMP_RESULT': ('RUN', 45),
    'MM_RUN_FOR_SEARCH_IDX': ('RUN', 46),
    'MM_RUN_TMP16': ('RUN', 47),
    'MM_RUN_STR_TMP_LEN': ('RUN', 49),
    'MM_RUN_STR_TMP_BUF': ('STRING_TMP', 0),
    'MM_RUN_SCAN_DEPTH': ('RUN', 81),
    'MM_RUN_GOSUB_SP': ('RUN', 82),
    'MM_RUN_FOR_SP': ('RUN', 83),
    'MM_RUN_TMP_E': ('RUN', 84),
    'MM_RUN_TMP_SHIFT': ('RUN', 85),
    'MM_RUN_TMP_M2': ('RUN', 86),
    'MM_RUN_TMP_M1': ('RUN', 87),
    'MM_RUN_TMP_M0': ('RUN', 88),
    'MM_RUN_TMP_RBIT': ('RUN', 89),
    'MM_RUN_VAR_FREE_PTR': ('VAR_FREE', 0),
    'MM_RUN_KW_TEXT': ('RUN_EXTRA_HEAD', 0),
    'MM_RUN_KW_LEN': ('RUN_EXTRA_HEAD', 2),
    'MM_LOGIC_TMP_RIGHT': ('RUN_EXTRA_HEAD', 3),
    'MM_RUN_CMP_OP': ('RUN_EXTRA_HEAD', 5),
    'MM_RUN_CMP_RAW': ('RUN_EXTRA_HEAD', 6),
    'MM_RUN_DATA_WANT_KIND': ('RUN_EXTRA_HEAD', 7),
    'MM_RUN_DATA_REC': ('DATA_POSITION', 0),
    'MM_RUN_DATA_PTR': ('DATA_POSITION', 2),
    'MM_RUN_DATA_END': ('DATA_POSITION', 4),
    'MM_RUN_DATA_STATE': ('DATA_POSITION', 6),
    'MM_RUN_DATA_MAIN_SAVE_PTR': ('DATA_WORK', 0),
    'MM_RUN_DATA_MAIN_SAVE_END': ('DATA_WORK', 2),
    'MM_RUN_DATA_NEG': ('DATA_WORK', 4),
    'MM_RUN_CONT_REC': ('CONT_POSITION', 0),
    'MM_RUN_CONT_PTR': ('CONT_POSITION', 2),
    'MM_RUN_CONT_END': ('CONT_POSITION', 4),
    'MM_RUN_ARITH_L': ('RUN_EXTRA_TAIL', 0),
    'MM_RUN_ARITH_R': ('RUN_EXTRA_TAIL', 2),
    'MM_SDIV_SIGNQ': ('RUN_EXTRA_TAIL', 4),
    'MM_SDIV_SIGNR': ('RUN_EXTRA_TAIL', 5),
    'MM_RUN_POW_EXP': ('RUN_EXTRA_TAIL', 6),
    'MM_RUN_POW_NEG': ('RUN_EXTRA_TAIL', 8),
    'MM_RUN_POW_COUNT': ('RUN_EXTRA_TAIL', 9),
    'MM_RUN_POW_BASE': ('RUN_EXTRA_TAIL', 11),
    'MM_RUN_VAL_SAVE9': ('RUN_EXTRA_TAIL', 20),
    'MM_RUN_ARRAY_IDX': ('RUN_EXTRA_TAIL', 29),
    'MM_RUN_ARRAY_FREE_PTR': ('RUN_EXTRA_TAIL', 31),
    'MM_RUN_ARRAY_NAME': ('RUN_EXTRA_TAIL', 33),
    'MM_RUN_DIM_COUNT': ('RUN_EXTRA_TAIL', 41),
    'MM_RUN_IF_TRUE': ('RUN_EXTRA_TAIL', 42),
    'MM_RUN_ERROR_HANDLER_LINE': ('ON_ERROR', 0),
    'MM_RUN_ERROR_ACTIVE': ('ON_ERROR', 2),
    'MM_RUN_LAST_ERR': ('ON_ERROR', 3),
    'MM_RUN_STR_ARG1_LEN': ('STR_ARG_LEN', 0),
    'MM_RUN_STR_ARG1_BUF': ('STRING_ARG', 0),
    'MM_RUN_STR_ACC_LEN': ('STR_ACC_LEN', 0),
    'MM_RUN_STR_ACC_BUF': ('STRING_ACC', 0),
    'MM_RUN_ARG1': ('RUN_INPUT', 0),
    'MM_PNFM_SAVE_PTR': ('RUN_INPUT', 2),
    'MM_PNFM_SAVE_END': ('RUN_INPUT', 4),
    'MM_PNFM_NEG': ('RUN_INPUT', 6),
    'MM_RUN_INPUT_COUNT': ('RUN_INPUT', 7),
    'MM_RUN_INPUT_VARS': ('RUN_INPUT', 8),
    'MM_RUN_INPUT_RAW_LEN': ('RUN_INPUT', 44),
    'MM_RUN_INPUT_RAW_BUF': ('RUN_INPUT', 45),
    'MM_RUN_ARRAY_ASSIGN_ADDR': ('RUN_INPUT', 85),
    'MM_RUN_LOCATE_COL': ('RUN_INPUT', 87),
    'MM_KEY_OLD': ('KEY_OLD', 0),
    'MM_KEY_NEW': ('KEY_NEW', 0),
    'MM_VAR_LINELEN': ('LINE', 0),
    'MM_LINE_BUF': ('LINE', 1),
    'MM_VAR_INSMODE': ('LINE', 81),
    'MM_REPEAT_KIND': ('REPEAT', 0),
    'MM_REPEAT_PORT': ('REPEAT', 1),
    'MM_REPEAT_MASK': ('REPEAT', 2),
    'MM_REPEAT_PHASE': ('REPEAT', 3),
    'MM_REPEAT_COUNTER': ('REPEAT', 4),
    'MM_REPEAT_CHAR': ('REPEAT', 5),
    'MM_TEXT_BASE': ('TEXT', 0),
    'MM_VAR_ROW': ('SCREEN', 0),
    'MM_VAR_COL': ('SCREEN', 1),
    'MM_VAR_ROWBASE': ('SCREEN', 2),
    'MM_STMT_KIND': ('PROGRAM_WORK', 0),
    'MM_PROG_TMP16': ('PROGRAM_WORK', 1),
    'MM_PROG_DIGIT': ('PROGRAM_WORK', 3),
    'MM_PROG_CUR_LINENO': ('PROGRAM_WORK', 5),
    'MM_PROG_CUR_LNLEN': ('PROGRAM_WORK', 7),
    'MM_PROG_CUR_TEXTLEN': ('PROGRAM_WORK', 8),
    'MM_PROG_DEL_SRC': ('PROGRAM_WORK', 9),
    'MM_PROG_DEL_DST': ('PROGRAM_WORK', 11),
    'MM_PROG_INS_AT': ('PROGRAM_WORK', 13),
    'MM_PROG_INS_SIZE': ('PROGRAM_WORK', 15),
    'MM_PROG_TMP_SRC_LAST': ('PROGRAM_WORK', 17),
    'MM_PROG_TMP_DST_LAST': ('PROGRAM_WORK', 19),
    'MM_PROG_TMP_DST2': ('PROGRAM_WORK', 21),
    'MM_PROG_REND_PTR': ('PROGRAM_WORK', 23),
    'MM_PROG_REND_LEN': ('PROGRAM_WORK', 25),
    'MM_PROG_REND_MODE': ('PROGRAM_WORK', 26),
    'MM_PROG_REND_INNAME': ('PROGRAM_WORK', 27),
    'MM_PROG_REND_PREV': ('PROGRAM_WORK', 28),
    'MM_ERROR_FLAG': ('LEXER', 0),
    'MM_LINE_END': ('LEXER', 1),
    'MM_CUR_PTR': ('LEXER', 3),
    'MM_SUPPRESS_NL': ('LEXER', 5),
    'MM_MATCH_FOUND': ('LEXER', 6),
    'MM_MATCH_LEN': ('LEXER', 7),
    'MM_MATCH_TOKLEN': ('LEXER', 8),
    'MM_MATCH_TOK0': ('LEXER', 9),
    'MM_MATCH_TOK1': ('LEXER', 10),
    'MM_LMW_INPUT_PTR': ('LEXER', 11),
    'MM_LMW_AVAIL': ('LEXER', 13),
    'MM_LMW_TABPTR': ('LEXER', 14),
    'MM_LMW_WORDLEN': ('LEXER', 16),
    'MM_SELFTEST_PASS': ('LEXER', 17),
    'MM_SELFTEST_FAILIX': ('LEXER', 18),
    'MM_SELFTEST_TOTAL': ('LEXER', 19),
    'MM_SELFTEST_TABPTR': ('LEXER', 20),
    'MM_LST_EXPECT_LEN': ('LEXER', 22),
    'MM_LST_EXPECT_B0': ('LEXER', 23),
    'MM_LST_EXPECT_B1': ('LEXER', 24),
    'MM_LST_ENTRY_WORDLEN': ('LEXER', 25),
    'MM_MBF_DOPB_RAM': ('DOUBLE', 8),
    'MM_MBF_DRES_RAM': ('DOUBLE', 16),
    'MM_SQR_X': ('SQR', 0),
    'MM_SQR_Y': ('SQR', 8),
    'MM_SQR_ITER_LEFT': ('SQR', 16),
    'MM_SC_X': ('SINCOS', 0),
    'MM_SC_Y': ('SINCOS', 4),
    'MM_SC_N': ('SINCOS', 8),
    'MM_SC_FRAC': ('SINCOS', 12),
    'MM_SC_QUAD': ('SINCOS', 16),
    'MM_SC_QNUM': ('SINCOS', 20),
    'MM_SC_SUB': ('SINCOS', 24),
    'MM_SC_REDUCED': ('SINCOS', 28),
    'MM_SC_X2': ('SINCOS', 32),
    'MM_SC_ACC': ('SINCOS', 36),
    'MM_SC_RESULT': ('SINCOS', 40),
    'MM_SC_TMP_A': ('SINCOS', 44),
    'MM_SC_TAN_X': ('SINCOS', 48),
    'MM_SC_SINVAL': ('SINCOS', 52),
    'MM_SC_COSVAL': ('SINCOS', 56),
    'MM_SC_Q': ('SINCOS', 60),
    'MM_SC_NEG': ('SINCOS', 61),
    'MM_AEL_ATN_X': ('ATN', 0),
    'MM_AEL_ATN_XPS': ('ATN', 4),
    'MM_AEL_ATN_NUM': ('ATN', 8),
    'MM_AEL_ATN_RESULT': ('ATN', 12),
    'MM_AEL_ATN_NEG': ('ATN', 16),
    'MM_AEL_ATN_PI6': ('ATN', 17),
    'MM_AEL_ATN_PI2': ('ATN', 18),
    'MM_AEL_EXP_Y': ('EXP', 0),
    'MM_AEL_EXP_NY': ('EXP', 4),
    'MM_AEL_EXP_FRAC': ('EXP', 8),
    'MM_AEL_EXP_POLY': ('EXP', 12),
    'MM_AEL_EXP_POW2': ('EXP', 16),
    'MM_AEL_LOG_M': ('LOG', 0),
    'MM_AEL_LOG_P': ('LOG', 4),
    'MM_AEL_LOG_Q': ('LOG', 8),
    'MM_AEL_LOG_PQ': ('LOG', 12),
    'MM_AEL_LOG_EFLOAT': ('LOG', 16),
    'MM_AEL_LOG_LOG2X': ('LOG', 20),
    'MM_AEL_POLY_VAR': ('POLY', 0),
    'MM_AEL_POLY_ACC': ('POLY', 4),
    'MM_AEL_TMP_SHIFT': ('POLY', 8),
    'MM_RND_X': ('RND', 0),
    'MM_RND_INDEX': ('RND', 4),
    'MM_RND_COUNT': ('RND', 5),
    'MM_RND_SEED': ('RND', 6),
    'MM_MAIN_SUB_SECTOR_BUF': ('SECTOR', 0),
    'MM_FILES_FAT_BUF': ('FILES_FAT', 0),
    'MM_FILES_CELL_BUF': ('FILES', 0),
    'MM_FILES_PHASE': ('FILES', 16),
    'MM_FILES_READ_TRACK': ('FILES', 18),
    'MM_FILES_READ_SECTOR': ('FILES', 19),
    'MM_FILES_READ_OK': ('FILES', 20),
    'MM_FILES_DIR_SECTOR': ('FILES', 21),
    'MM_FILES_ENTRY_INDEX': ('FILES', 22),
    'MM_FILES_ENTRY_COUNT': ('FILES', 23),
    'MM_FILES_CHAIN_GUARD': ('FILES', 24),
    'MM_FILES_SIZE_VALUE': ('FILES', 25),
    'MM_FILES_DEC_STARTED': ('FILES', 26),
    'MM_LOAD_PHASE': ('LOAD', 0),
    'MM_LOAD_NAME': ('LOAD', 1),
    'MM_LOAD_READ_TRACK': ('LOAD', 12),
    'MM_LOAD_READ_SECTOR': ('LOAD', 13),
    'MM_LOAD_READ_OK': ('LOAD', 14),
    'MM_LOAD_DIR_SECTOR': ('LOAD', 15),
    'MM_LOAD_ENTRY_INDEX': ('LOAD', 16),
    'MM_LOAD_UNIT': ('LOAD', 17),
    'MM_LOAD_UNIT_SECTOR': ('LOAD', 18),
    'MM_LOAD_BYTE_OFFSET': ('LOAD', 19),
    'MM_LOAD_LINE_LEN': ('LOAD', 20),
    'MM_LOAD_SKIP_LF': ('LOAD', 21),
    'MM_LOAD_CHAIN_GUARD': ('LOAD', 22),
    'MM_FILES_DRIVE': ('FILES', 17),
    'MM_LOAD_NAME_LEN': ('LOAD', 10),
    'MM_LOAD_DRIVE': ('LOAD', 11),
    'MM_S2_NAME': ('SAVE', 16),
    'MM_S2_DRIVE': ('SAVE', 25),
    'MM_S2_NAMELEN': ('SAVE', 26),
    'MM_S2_DIRSEC': ('SAVE', 27),
    'MM_S2_DIRIDX': ('SAVE', 28),
    'MM_S2_CHOSEN': ('SAVE', 29),
    'MM_S2_FOUND': ('SAVE', 30),
    'MM_S2_OLDUNIT': ('SAVE', 31),
    'MM_S2_SECTORS': ('SAVE', 32),
    'MM_S2_UNITS': ('SAVE', 33),
    'MM_S2_INDEX': ('SAVE', 34),
    'MM_S2_COUNT': ('SAVE', 35),
    'MM_S2_UNIT': ('SAVE', 36),
    'MM_S2_NEXT': ('SAVE', 37),
    'MM_S2_TRACK': ('SAVE', 38),
    'MM_S2_SECTOR': ('SAVE', 39),
    'MM_S2_SLOTIDX': ('SAVE', 40),
    'MM_S2_FAT': ('SAVE_FAT', 0),
    'MM_S2_ALLOC': ('SAVE_ALLOC', 0),
    'MM_S2_CAPTURE_LEN': ('SAVE', 3),
    'MM_S2_CAPTURE_ACTIVE': ('SAVE', 0),
    'MM_S2_CAPTURE_PTR': ('SAVE', 1),
    'MM_S2_DONE': ('SAVE', 11),
    'MM_S2_WRITE_COUNT': ('SAVE', 12),
    'MM_S2_WRITE_DRIVE': ('SAVE', 6),
    'MM_S2_WRITE_TRACK': ('SAVE', 7),
    'MM_S2_WRITE_SECTOR': ('SAVE', 8),
    'MM_S2_WRITE_SOURCE': ('SAVE', 9),
    'MM_K2_MATCH_KIND': ('SAVE', 54),
    'MM_K2_MATCH_LEN': ('SAVE', 55),
    'MM_K2_OLDSEC': ('SAVE', 41),
    'MM_K2_OLDSLOT': ('SAVE', 42),
    'MM_K2_OLDDRIVE': ('SAVE', 43),
    'MM_B3_CAPTURE_IN': ('SAVE', 13),
    'MM_IK_VRTC': ('INKEY', 0),
    'MM_IK_HEAD': ('INKEY', 1),
    'MM_IK_TAIL': ('INKEY', 2),
    'MM_IK_COUNT': ('INKEY', 3),
    'MM_IK_OLD': ('INKEY', 4),
    'MM_IK_PORT': ('INKEY', 16),
    'MM_IK_MASK': ('INKEY', 17),
    'MM_IK_CHAR': ('INKEY', 18),
    'MM_IK_TIMER': ('INKEY', 19),
    'MM_IK_MOD': ('INKEY', 20),
    'MM_IK_CAPS': ('INKEY', 21),
    'MM_IK_EVENT': ('INKEY', 22),
    'MM_IK_TICK': ('INKEY', 23),
    'MM_IK_BUF': ('INKEY_QUEUE', 0),
    'MM_EXT_BANK_BUSY': ('RELAY', 0),
    'MM_EXT_BANK_REENTRY_DETECTED': ('RELAY', 1),
    'MM_MAIN_SUB_LOGICAL_SENT': ('DISK_CHR', 2),
    'MM_EXT_BANK_MAIN_PORT71': ('RELAY', 2),
    'MM_EXT_BANK_MAIN_PORT32': ('RELAY', 3),
    'MM_EXT_BANK_ST_VAL0': ('EXT_TEST_LOW', 0),
    'MM_EXT_BANK_ST_VAL1': ('EXT_TEST_LOW', 1),
    'MM_EXT_BANK_ST_VAL2': ('EXT_TEST_LOW', 2),
    'MM_EXT_BANK_ST_VAL3': ('EXT_TEST_LOW', 3),
    'MM_EXT_BANK_ST_PASS': ('EXT_TEST_LOW', 4),
    'MM_EXT_BANK_ST_WINCALL': ('EXT_TEST_LOW', 5),
    'MM_EXT_BANK_ST_LOOP_DONE': ('EXT_TEST_LOW', 6),
    'MM_EXT_BANK_ST_LOOP_OK': ('EXT_TEST_LOW', 7),
    'MM_EXT_BANK_ST_LOOP_CNT': ('EXT_TEST_HIGH', 0),
    'MM_EXT_BANK_ST_ABS_VAL': ('EXT_TEST_HIGH', 3),
    'MM_EXT_BANK_ST_ABS_OK': ('EXT_TEST_HIGH', 2),
    'MM_EXT_BANK_ST_MBF_OK': ('EXT_TEST_HIGH', 4),
    'MM_MAIN_SUB_MARK_REQUEST': ('DISK_STATE', 0),
    'MM_MAIN_SUB_MARK_RECV256': ('DISK_STATE', 1),
    'MM_MAIN_SUB_MARK_SUCCESS': ('DISK_STATE', 2),
    'MM_MAIN_SUB_MARK_TIMEOUT': ('DISK_STATE', 3),
    'MM_MAIN_SUB_MARK_FAULT_WAIT': ('DISK_STATE', 4),
    'MM_MAIN_SUB_MARK_FAULT_CONT': ('DISK_STATE', 5),
    'MM_MAIN_SUB_MARK_FAULT_PAIR': ('DISK_STATE', 6),
    'MM_MAIN_SUB_DRIVE_SELECT': ('DISK_STATE', 7),
    'MM_MAIN_SUB_BOOT_DONE': ('DISK_STATE', 8),
    'MM_MAIN_SUB_CHR_LOGICAL_TRACK': ('DISK_CHR', 0),
    'MM_MAIN_SUB_CHR_SECTOR': ('DISK_CHR', 1),
    'MM_VSYNC_REGCHECK_DONE': ('VSYNC_TEST', 0),
    'MM_VSYNC_REGCHECK_RESULT': ('VSYNC_TEST', 1),
    'MM_VSYNC_REGCHECK_SAVE_A': ('VSYNC_TEST', 2),
    'MM_VSYNC_REGCHECK_SAVE_BC': ('VSYNC_TEST', 3),
    'MM_VSYNC_REGCHECK_SAVE_DE': ('VSYNC_TEST', 5),
    'MM_VSYNC_REGCHECK_SAVE_HL': ('VSYNC_TEST', 7),
    'MM_VSYNC_REGCHECK_SAVE_IX': ('VSYNC_TEST', 9),
    'MM_VSYNC_REGCHECK_SAVE_IY': ('VSYNC_TEST', 11),
    'MM_LN_CHECKONLY': ('LIST', 207),
    'MM_LN_INPUT': ('LIST', 0),
    'MM_LN_OUTPUT': ('LIST', 96),
    'MM_LN_SRC': ('LIST', 176),
    'MM_LN_DST': ('LIST', 178),
    'MM_LN_PREFIX': ('LIST', 180),
    'MM_LN_MODE': ('LIST', 181),
    'MM_LN_NAME': ('LIST', 182),
    'MM_LN_KIND': ('LIST', 183),
    'MM_LN_DOT': ('LIST', 184),
    'MM_LN_EXP': ('LIST', 185),
    'MM_LN_VALUE': ('LIST', 186),
    'MM_LN_BIG': ('LIST', 188),
    'MM_LN_BASE': ('LIST', 189),
    'MM_LN_ERR': ('LIST', 190),
    'MM_LN_NDIG': ('LIST', 191),
    'MM_LN_DIGBUF': ('LIST', 192),
    'MM_LN_DFOUT_BUF': ('DOUBLE', 133),
    'MM_LN_DFOUT_LEN': ('DOUBLE', 157),
    'MM_S9_REC': ('STRING_WORK', 0),
    'MM_S9_START': ('STRING_WORK', 2),
    'MM_S9_TARGET_LEN': ('STRING_WORK', 3),
    'MM_S9_NEEDLE_LEN': ('STRING_WORK', 4),
    'MM_S9_POS': ('STRING_WORK', 5),
    'MM_S9_BASE': ('STRING_WORK', 6),
    'MM_S9_DIGITS': ('STRING_WORK', 7),
    'MM_S9_DIGBUF': ('STRING_WORK', 8),
    'MM_S9_RESUME_REC': ('RESUME', 0),
    'MM_S9_RESUME_PTR': ('RESUME', 2),
    'MM_S9_RESUME_END': ('RESUME', 4),
    'MM_S9E_L_LEN': ('STRCMP', 0),
    'MM_S9E_L_BUF': ('STRCMP', 1),
    'MM_STACK_TOP': ('CPU_STACK', 400),
    'MM_STRING_FLAGS': ('STRING_USED', 0),
    'MM_S9_RESUME_SKIP': ('STRING_WORK', 15),
    'MM_STMT_START': ('STMT_START', 0),
    'MM_M6IB_FRAME_COUNT': ('MEASURE_LOW', 0),
    'MM_M6IB_STAGE': ('MEASURE_LOW', 1),
    'MM_M6IB_MARK_B': ('MEASURE_LOW', 2),
    'MM_M6IB_MARK_C': ('MEASURE_LOW', 3),
    'MM_M6IH_MARK_RETRY': ('MEASURE_LOW', 4),
    'MM_M6II_ROW_MARKER': ('MEASURE_HIGH', 2),
    'MM_M6IK_ROW_MARKER': ('MEASURE_HIGH', 3),
    'MM_M6IK_PRE_MARKER': ('MEASURE_HIGH', 4),
    'MM_M6IK_NEXT_ROW': ('MEASURE_HIGH', 5),
}


# ソースの既存名 -> 正典名。番地のコピーを持たない別名。
ALIASES = {
    'AEL_TRUNC_HADFRAC': 'MM_TRUNC_HADFRAC',
    'AEL_TRUNC_SIGN': 'MM_TRUNC_SIGN',
    'B1_ERROR_FLAG': 'MM_ERROR_FLAG',
    'B1_ERROR_KIND': 'MM_ERROR_KIND',
    'B1_LINE_BUF': 'MM_LINE_BUF',
    'B1_RUN_CTRL': 'MM_RUN_CTRL',
    'B1_RUN_ERROR_ACTIVE': 'MM_RUN_ERROR_ACTIVE',
    'B1_RUN_ERROR_HANDLER_LINE': 'MM_RUN_ERROR_HANDLER_LINE',
    'B1_VAR_LINELEN': 'MM_VAR_LINELEN',
    'B3_CAPTURE_LEN': 'MM_S2_CAPTURE_LEN',
    'B3_CAPTURE_PTR': 'MM_S2_CAPTURE_PTR',
    'K2_CUR_PTR': 'MM_CUR_PTR',
    'K2_LINE_END': 'MM_LINE_END',
    'LN_DOPA': 'MM_MBF_DOUBLE_RAM_BASE',
    'LN_DRES': 'MM_MBF_DRES_RAM',
    'LN_FIN_BUF': 'MM_FIN_BUF',
    'LN_FIN_LEN': 'MM_FIN_LEN',
    'LN_FOUT_BUF': 'MM_FOUT_BUF',
    'LN_FOUT_LEN': 'MM_FOUT_LEN',
    'LN_LINE_BUF': 'MM_LINE_BUF',
    'LN_LINE_LEN': 'MM_VAR_LINELEN',
    'LN_OPA': 'MM_MBF_OPA',
    'LN_RES': 'MM_MBF_RES',
    'LN_STATUS': 'MM_MBF_STATUS',
    'LOAD_LINE_BUF': 'MM_LINE_BUF',
    'MBF_DOPA_RAM': 'MM_MBF_DOUBLE_RAM_BASE',
        'RND_ACC0': 'MM_FIN_ACC0',
    'RND_ACC1': 'MM_FIN_ACC1',
    'RND_ACC2': 'MM_FIN_ACC2',
    'RND_ACC3': 'MM_FIN_ACC3',
    'RND_FIN_SIGN': 'MM_FIN_SIGN',
    'S2_BUF': 'MM_MAIN_SUB_SECTOR_BUF',
    'S2_ERROR_FLAG': 'MM_ERROR_FLAG',
    'S2_ERROR_KIND': 'MM_ERROR_KIND',
    'S9_ARG': 'MM_RUN_STR_ARG1_BUF',
    'S9_CUR_DATA': 'MM_CUR_DATA',
    'S9_CUR_TYPE': 'MM_CUR_TYPE',
    'S9_TMP': 'MM_RUN_STR_TMP_BUF',
    'S9_TMP_LEN': 'MM_RUN_STR_TMP_LEN',
    'SAVE_CAPTURE_ACTIVE': 'MM_S2_CAPTURE_ACTIVE',
    'SAVE_CAPTURE_IN': 'MM_B3_CAPTURE_IN',
    'SAVE_DONE_FLAG': 'MM_S2_DONE',
}

CONSTANTS = {
    "MM_USER_START": 0x8400,
    "MM_USER_LIMIT_DEFAULT": 0xE5FF,
    "MM_USER_STACK_SIZE": 512,
    "MM_STRING_PAGE_COUNT": 96,
    "MM_PROGRAM_AREA": 0x8400,
    "MM_SYNTH_DATA": 0x8400,
}
DYNAMIC_STRUCTURES = {
    "PROGRAM": "USER_STARTから番兵まで",
    "HEAP": "番兵直後HEAP_STARTからHEAP_ENDまで、種別1=42B/2=298Bを追記",
    "STRING_PAGES": "LIMIT-511の下から256Bずつ下向き、使用ビット表で管理",
    "FOR_STACK": "LIMIT-511から24B×8",
    "GOSUB_STACK": "FOR先頭+192から6B×8（512B内）",
    "CAPTURE": "HEAP_ENDからFREE_TOPまでの空き（SAVE中のみ）",
}

def addresses():
    regions = {r.name: r for r in REGIONS}
    return CONSTANTS | {name: regions[region].base + offset
            for name, (region, offset) in FIELDS.items()}


def asm_prelude():
    """独立したアセンブル単位の先頭へ一度だけ付ける（バイトは出さない）。"""
    values = addresses()
    values.update({"MM_" + r.name + "_SIZE": r.size for r in REGIONS})
    return "; src/memmap.py から生成したRAM定義\n" + "".join(
        f"{name} EQU 0x{value:04X}\n" for name, value in values.items())
